import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { Linkedin, Twitter } from 'lucide-react';
const footerLinks = [
    { label: 'Privacy', href: '/privacy' },
    { label: 'Terms', href: '/terms' },
    { label: 'Access Statement', href: '/accessibility' },
];
const Footer = () => {
    return (_jsxs("footer", { className: "mt-16 border-t border-mist/60 bg-[var(--hud-bg)]", children: [_jsxs("div", { className: "mx-auto flex max-w-7xl flex-col gap-8 px-6 py-10 lg:flex-row lg:items-center lg:justify-between lg:px-12", children: [_jsx("a", { href: "/", "aria-label": "Return to home", className: "flex items-center gap-3 no-underline", children: _jsx("img", { src: "/logo.svg", alt: "Huddle Co.", className: "h-12 w-12 rounded-2xl shadow-card-sm" }) }), _jsx("nav", { className: "flex flex-wrap items-center gap-4 text-sm font-semibold text-slate/80", children: footerLinks.map((link) => (_jsx("a", { href: link.href, className: "hover:text-charcoal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-skyblue focus-visible:ring-offset-2 focus-visible:ring-offset-softwhite", children: link.label }, link.label))) }), _jsxs("div", { className: "flex items-center gap-3", children: [_jsx("a", { href: "https://linkedin.com", target: "_blank", rel: "noopener noreferrer", "aria-label": "LinkedIn", className: "inline-flex h-10 w-10 items-center justify-center rounded-full border border-mist text-slate/80 transition hover:text-sunrise focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-skyblue focus-visible:ring-offset-2 focus-visible:ring-offset-softwhite", children: _jsx(Linkedin, { className: "h-5 w-5", "aria-hidden": "true" }) }), _jsx("a", { href: "https://twitter.com", target: "_blank", rel: "noopener noreferrer", "aria-label": "Twitter", className: "inline-flex h-10 w-10 items-center justify-center rounded-full border border-mist text-slate/80 transition hover:text-sunrise focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-skyblue focus-visible:ring-offset-2 focus-visible:ring-offset-softwhite", children: _jsx(Twitter, { className: "h-5 w-5", "aria-hidden": "true" }) })] })] }), _jsx("div", { className: "px-6 lg:px-12 pb-6", children: _jsxs("div", { className: "mx-auto max-w-7xl flex flex-col items-center gap-3", children: [_jsx("img", { src: "/logo.svg", alt: "Huddle Co.", className: "h-10 w-10 rounded-2xl shadow-card-sm" }), _jsx("a", { href: "/brand-guidelines", className: "text-sm font-semibold text-slate/80 hover:text-charcoal focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-skyblue focus-visible:ring-offset-2 focus-visible:ring-offset-softwhite", children: "Brand Guidelines" })] }) }), _jsx("div", { className: "border-t border-mist/40 bg-white/70", children: _jsxs("p", { className: "mx-auto max-w-7xl px-6 py-4 text-sm text-slate/70 lg:px-12", children: ["\u00A9 ", new Date().getFullYear(), " The Huddle Co. All rights reserved."] }) })] }));
};
export default Footer;
