export {
  lessonSchema,
  lessonPatchSchema,
  moduleSchema,
  modulePatchSchema,
  lessonContentSchema,
  completionRuleSchema,
  moduleReorderSchema,
  lessonReorderSchema,
  type LessonInput,
  type LessonPatchInput,
  type ModuleInput,
  type ModulePatchInput,
  type ModuleReorderInput,
  type LessonReorderInput,
} from '../../shared/api/schemas';
