#!/usr/bin/env node
import fs from 'fs';
import { join } from 'path';
import sql from '../server/db.js';

const MIG_DIR = join(process.cwd(), 'supabase', 'migrations');
if (!fs.existsSync(MIG_DIR)) fs.mkdirSync(MIG_DIR, { recursive: true });

function sanitizeName(s) {
  return String(s).replace(/[^a-zA-Z0-9_]/g, '_').toLowerCase().slice(0, 60);
}

function timestamp() {
  const d = new Date();
  const pad = (n) => String(n).padStart(2, '0');
  return `${d.getUTCFullYear()}${pad(d.getUTCMonth()+1)}${pad(d.getUTCDate())}${pad(d.getUTCHours())}${pad(d.getUTCMinutes())}${pad(d.getUTCSeconds())}`;
}

async function run() {
  try {
    const rows = await sql`select schemaname, tablename, policyname, roles, cmd as action, qual, with_check, permissive from pg_policies order by schemaname, tablename`;
    if (!rows || rows.length === 0) {
      console.log('No pg_policies rows found.');
      return;
    }

    const map = new Map();
    for (const r of rows) {
      const perm = r.permissive;
      const isPermissive = (perm !== null && perm !== undefined) && String(perm).toLowerCase().includes('perm');
      if (!isPermissive) continue;

      // normalize roles
      let roleList = [];
      const rolesRaw = r.roles;
      if (Array.isArray(rolesRaw)) roleList = rolesRaw;
      else if (typeof rolesRaw === 'string') {
        const trimmed = rolesRaw.trim();
        if (trimmed.startsWith('{') && trimmed.endsWith('}')) roleList = trimmed.slice(1, -1).split(',').map(s => s.trim());
        else if (trimmed.length) roleList = [trimmed];
      } else if (rolesRaw == null) roleList = [];
      else roleList = [String(rolesRaw)];

      for (const role of roleList) {
        const roleName = String(role).replace(/^"|"$/g, '');
        const key = `${r.schemaname}.${r.tablename}::${roleName}::${r.action}`;
        if (!map.has(key)) map.set(key, { schemaname: r.schemaname, tablename: r.tablename, role: roleName, action: r.action, policies: [] });
        map.get(key).policies.push({ policyname: r.policyname, qual: r.qual, with_check: r.with_check });
      }
    }

    const generated = [];
    const needsManual = [];
    for (const [key, group] of map.entries()) {
      if (group.policies.length <= 1) continue;
      // check for unconditional
      const hasUnconditional = group.policies.some(p => !p.qual || String(p.qual).trim() === '' || String(p.qual).toLowerCase() === 'true' || String(p.qual).toLowerCase() === 'false');
      if (hasUnconditional) {
        needsManual.push(group);
        continue;
      }

      // build combined USING and WITH CHECK
      const quals = group.policies.map(p => `(${p.qual})`);
      const combinedUse = quals.join(' OR ');
      const checks = group.policies.map(p => p.with_check).filter(Boolean);
      const combinedCheck = checks.length ? checks.map(c => `(${c})`).join(' OR ') : null;

      const fileTimestamp = `${timestamp()}_${Math.floor(Math.random()*1000)}`;
      const fileName = `${fileTimestamp}_consolidate_rls_${sanitizeName(group.schemaname)}_${sanitizeName(group.tablename)}_${sanitizeName(group.role)}_${sanitizeName(String(group.action))}.sql`;
      const filePath = join(MIG_DIR, fileName);

      let content = `-- Consolidate multiple permissive RLS policies into one for ${group.schemaname}.${group.tablename}\n`;
      content += `-- Generated by scripts/generate_consolidation_migrations.mjs on ${new Date().toISOString()}\n\n`;
      content += `-- NOTE: This creates a consolidated policy combining existing USING conditions with OR.\n`;
      content += `-- Verify application behavior after applying. Keep backups of original policies until verified.\n\n`;
      content += `-- Optional: drop old policies after verification (commented out below)\n`;
      for (const p of group.policies) content += `-- DROP POLICY IF EXISTS ${p.policyname} ON ${group.schemaname}.${group.tablename};\n`;
      content += '\n';
      const suggestedPolicyName = `consolidated_${sanitizeName(group.role)}_${sanitizeName(String(group.action)).toLowerCase()}`;
      content += `CREATE POLICY ${suggestedPolicyName} ON ${group.schemaname}.${group.tablename} FOR ${String(group.action).toUpperCase()} TO ${group.role} USING (${combinedUse})${combinedCheck ? ` WITH CHECK (${combinedCheck})` : ''};\n`;
      content += `\n-- After verifying behavior, you may DROP the old policies and optionally rename this policy.\n`;

      fs.writeFileSync(filePath, content, { encoding: 'utf8' });
      generated.push(filePath);
    }

    // write a note file for manual groups
    if (needsManual.length) {
      const notePath = join(MIG_DIR, `MANUAL_REVIEW_CONSOLIDATION_${timestamp()}.md`);
      let note = `# Manual review required for consolidation (${new Date().toISOString()})\n\n`;
      note += `The following RLS policy groups contain unconditional or ambiguous USING clauses and need manual review before consolidation.\n\n`;
      for (const g of needsManual) {
        note += `- Table: ${g.schemaname}.${g.tablename}  Role: ${g.role}  Action: ${g.action}\n`;
        note += `  Policies:\n`;
        for (const p of g.policies) note += `    - ${p.policyname}  qual=${p.qual ? p.qual.replace(/\n+/g,' ') : '<null or unconditional>'}\n`;
        note += '\n';
      }
      fs.writeFileSync(notePath, note, 'utf8');
      console.log(`Manual review file written: ${notePath}`);
    }

    if (generated.length) {
      console.log('Generated consolidation migration files:');
      generated.forEach((f) => console.log(`  - ${f}`));
    } else {
      console.log('No safe consolidation migrations generated.');
    }

    if (generated.length === 0 && needsManual.length === 0) console.log('Nothing to do.');

  } catch (err) {
    console.error('Error generating consolidation migrations:', err?.message || String(err));
    process.exitCode = 1;
  } finally {
    await sql.end?.();
  }
}

run();
