#!/usr/bin/env node
/**
 * End-to-end API smoke tests that verify the core launch endpoints respond
 * with healthy payloads (or at least avoid 5xx errors).
 *
 * Auth:
 *   ADMIN_BEARER_TOKEN  - Supabase session token for an org admin (required)
 *   LEARNER_BEARER_TOKEN - Optional learner token; defaults to admin token
 *
 * Context:
 *   API_BASE_URL  - Defaults to http://localhost:8888/api
 *   GUARD_ORG_ID / SMOKE_ORG_ID - Organization UUID used for import/publish tests
 *
 * Usage: npm run test:api-smoke
 */

import fetch from 'node-fetch';
import { randomUUID } from 'node:crypto';

const API_BASE_URL = (process.env.API_BASE_URL || 'http://localhost:8888/api').replace(/\/$/, '');
const ADMIN_TOKEN = process.env.ADMIN_BEARER_TOKEN;
const LEARNER_TOKEN = process.env.LEARNER_BEARER_TOKEN || ADMIN_TOKEN;
const ORG_ID = process.env.GUARD_ORG_ID || process.env.SMOKE_ORG_ID;

if (!ADMIN_TOKEN) {
  console.error('❌ ADMIN_BEARER_TOKEN env var is required for admin API smoke tests.');
  process.exit(1);
}
if (!ORG_ID) {
  console.error('❌ GUARD_ORG_ID (or SMOKE_ORG_ID) env var is required.');
  process.exit(1);
}

const SMOKE_IDS = {
  course: '11111111-2222-4333-9444-555555555555',
  module: '66666666-7777-4888-9999-000000000000',
  lesson: 'aaaaaaaa-bbbb-4ccc-8ddd-eeeeeeeeeeee',
};

async function request(path, { method = 'GET', body, token, expect = 200 } = {}) {
  const headers = { 'Content-Type': 'application/json' };
  if (token) headers.Authorization = `Bearer ${token}`;
  const res = await fetch(`${API_BASE_URL}${path}`, {
    method,
    headers,
    body: body ? JSON.stringify(body) : undefined,
  });
  if (res.status >= 500) {
    const text = await res.text();
    throw new Error(`${method} ${path} returned ${res.status}: ${text}`);
  }
  if (res.status !== expect) {
    const text = await res.text();
    throw new Error(`${method} ${path} expected ${expect} but returned ${res.status}: ${text}`);
  }
  const contentType = res.headers.get('content-type') || '';
  if (!contentType.includes('application/json')) {
    throw new Error(`${method} ${path} did not return JSON (content-type: ${contentType})`);
  }
  return res.json();
}

function logPass(name) {
  console.log(`✅ ${name}`);
}

async function run() {
  await request('/health', { expect: 200 });
  logPass('GET /api/health');

  const coursesList = await request(`/admin/courses?orgId=${ORG_ID}&includeStructure=true`, {
    token: ADMIN_TOKEN,
  });
  if (!Array.isArray(coursesList.data) || coursesList.data.length === 0) {
    throw new Error('Admin course list returned no data. Seed at least one course.');
  }
  logPass('GET /api/admin/courses');

  const targetCourse = coursesList.data[0];
  await request(`/admin/courses/${targetCourse.id}`, { token: ADMIN_TOKEN });
  logPass('GET /api/admin/courses/:id');

  const smokeCoursePayload = {
    items: [
      {
        index: 0,
        overwrite: true,
        course: {
          id: SMOKE_IDS.course,
          organization_id: ORG_ID,
          slug: 'schema-guard-smoke',
          title: 'Schema Guard Smoke Course',
          description: 'Autogenerated course used by schema guardrail tests.',
          status: 'draft',
          meta: { source: 'schema-guard' },
        },
        modules: [
          {
            id: SMOKE_IDS.module,
            title: 'Smoke Module',
            description: 'Autogenerated module',
            order_index: 1,
            lessons: [
              {
                id: SMOKE_IDS.lesson,
                title: 'Smoke Lesson',
                type: 'text',
                order_index: 1,
                content_json: {
                  type: 'text',
                  body: {
                    title: 'Smoke Lesson',
                    content: 'Autogenerated content',
                    description: 'Smoke lesson body',
                    schema_version: 1,
                  },
                },
              },
            ],
          },
        ],
      },
    ],
    overwrite: true,
    publishMode: 'draft',
    orgId: ORG_ID,
  };
  await request('/admin/courses/import', {
    method: 'POST',
    token: ADMIN_TOKEN,
    body: smokeCoursePayload,
    expect: 201,
  });
  logPass('POST /api/admin/courses/import');

  await request(`/admin/courses/${SMOKE_IDS.course}/publish`, {
    method: 'POST',
    token: ADMIN_TOKEN,
    body: { publishMode: 'published', orgId: ORG_ID },
  });
  logPass('POST /api/admin/courses/:id/publish');

  const catalog = await request('/client/courses', { token: LEARNER_TOKEN });
  if (!Array.isArray(catalog.data)) {
    throw new Error('Learner catalog response missing `data` array.');
  }
  logPass('GET /api/client/courses');

  await request(`/client/courses/schema-guard-smoke`, { token: LEARNER_TOKEN });
  logPass('GET /api/client/courses/:slug');

  const progressPayload = {
    events: [
      {
        client_event_id: randomUUID(),
        user_id: randomUUID(),
        course_id: SMOKE_IDS.course,
        lesson_id: SMOKE_IDS.lesson,
        org_id: ORG_ID,
        percent: 10,
        status: 'in_progress',
        event_type: 'lesson_progress',
        occurred_at: new Date().toISOString(),
      },
    ],
  };
  await request('/client/progress/batch', {
    method: 'POST',
    token: LEARNER_TOKEN,
    body: progressPayload,
  });
  logPass('POST /api/client/progress/batch');

  console.log('🎉 API smoke tests completed successfully.');
}

run().catch((error) => {
  console.error('❌ API smoke tests failed:', error.message);
  process.exit(1);
});
