#!/usr/bin/env node
/**
 * Smoke-tests the critical Postgres functions this LMS depends on.
 *
 * Tests covered:
 *  - upsert_course_graph inserts full course/module/lesson graphs
 *  - upsert_course_graph handles publish transitions
 *  - upsert_progress_batch records course + lesson progress rows
 *
 * Each test runs inside its own transaction and rolls back automatically,
 * so it is safe to run against staging/production databases.
 *
 * Usage: npm run test:db-functions
 */

import { Client } from 'pg';
import { randomUUID } from 'node:crypto';

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) {
  console.error('❌ DATABASE_URL is required to run DB function tests.');
  process.exit(1);
}

const client = new Client({ connectionString: DATABASE_URL });

const results = [];

async function resolveOrgId() {
  if (process.env.GUARD_ORG_ID) return process.env.GUARD_ORG_ID;
  if (process.env.SMOKE_ORG_ID) return process.env.SMOKE_ORG_ID;
  const { rows } = await client.query(`select id from organizations order by updated_at desc nulls last limit 1`);
  if (rows.length === 0) {
    throw new Error('No organizations found. Set GUARD_ORG_ID to a valid organization UUID.');
  }
  return rows[0].id;
}

async function runTest(name, fn) {
  await client.query('BEGIN');
  try {
    await fn();
    await client.query('ROLLBACK');
    console.log(`✅ ${name}`);
    results.push({ name, success: true });
  } catch (error) {
    await client.query('ROLLBACK');
    console.error(`❌ ${name}: ${error.message}`);
    results.push({ name, success: false, error });
  }
}

function buildLessonContent(title) {
  return {
    type: 'text',
    body: {
      title,
      content: 'Smoke content',
      description: 'Autogenerated test content',
      textContent: 'Smoke content',
      schema_version: 1,
    },
  };
}

async function upsertCourseGraph({ payload, orgId }) {
  const { rows } = await client.query(
    `select public.upsert_course_graph($1::jsonb, $2::uuid, $3::uuid) as result`,
    [payload, process.env.GUARD_ACTOR_ID ?? null, orgId],
  );
  return rows[0]?.result;
}

await client.connect();

await runTest('upsert_course_graph inserts modules and lessons', async () => {
  const orgId = await resolveOrgId();
  const courseId = randomUUID();
  const moduleId = randomUUID();
  const lessonId = randomUUID();
  const slug = `db-smoke-${Date.now()}`;
  const payload = {
    id: courseId,
    slug,
    title: 'DB Guard Smoke Course',
    description: 'Automated verification payload',
    status: 'draft',
    version: 1,
    meta_json: { source: 'schema-guard' },
    modules: [
      {
        id: moduleId,
        title: 'Module',
        description: 'Smoke module',
        order_index: 1,
        lessons: [
          {
            id: lessonId,
            title: 'Lesson',
            type: 'text',
            order_index: 1,
            content_json: buildLessonContent('Lesson'),
          },
        ],
      },
    ],
  };

  const saved = await upsertCourseGraph({ payload, orgId });
  if (!saved || saved.slug !== slug) {
    throw new Error('upsert_course_graph did not return the saved course.');
  }
  const { rows: lessonRows } = await client.query(`select id from lessons where id = $1`, [lessonId]);
  if (lessonRows.length === 0) {
    throw new Error('lesson row was not written by upsert_course_graph');
  }
});

await runTest('upsert_course_graph updates publish metadata', async () => {
  const orgId = await resolveOrgId();
  const courseId = randomUUID();
  const moduleId = randomUUID();
  const lessonId = randomUUID();
  const slug = `db-publish-${Date.now()}`;

  const draftPayload = {
    id: courseId,
    slug,
    title: 'DB Guard Publish Course',
    description: 'Publish smoke payload',
    status: 'draft',
    version: 1,
    modules: [
      {
        id: moduleId,
        title: 'Publish Module',
        order_index: 1,
        lessons: [
          {
            id: lessonId,
            title: 'Publish Lesson',
            type: 'text',
            order_index: 1,
            content_json: buildLessonContent('Publish Lesson'),
          },
        ],
      },
    ],
  };

  await upsertCourseGraph({ payload: draftPayload, orgId });

  const publishPayload = {
    ...draftPayload,
    status: 'published',
    version: 2,
  };
  await upsertCourseGraph({ payload: publishPayload, orgId });

  const { rows } = await client.query(
    `select status, published_at from courses where id = $1`,
    [courseId],
  );
  if (rows.length === 0) throw new Error('course not found after publish');
  if (rows[0].status !== 'published') {
    throw new Error(`course status expected "published" but was "${rows[0].status}"`);
  }
  if (!rows[0].published_at) {
    throw new Error('published_at was not set during publish');
  }
});

await runTest('upsert_progress_batch records course and lesson progress', async () => {
  const orgId = await resolveOrgId();
  const courseId = randomUUID();
  const moduleId = randomUUID();
  const lessonId = randomUUID();

  const payload = {
    id: courseId,
    slug: `db-progress-${Date.now()}`,
    title: 'DB Guard Progress Course',
    status: 'published',
    version: 1,
    modules: [
      {
        id: moduleId,
        title: 'Progress Module',
        order_index: 1,
        lessons: [
          {
            id: lessonId,
            title: 'Progress Lesson',
            type: 'text',
            order_index: 1,
            content_json: buildLessonContent('Progress Lesson'),
          },
        ],
      },
    ],
  };

  await upsertCourseGraph({ payload, orgId });

  const event = {
    client_event_id: randomUUID(),
    user_id: randomUUID(),
    course_id: courseId,
    lesson_id: lessonId,
    org_id: orgId,
    percent: 42,
    status: 'in_progress',
    event_type: 'lesson_progress',
    occurred_at: new Date().toISOString(),
  };

  const { rows } = await client.query(
    `select public.upsert_progress_batch($1::jsonb) as result`,
    [JSON.stringify([event])],
  );
  const rpcResult = rows[0]?.result;
  if (!rpcResult || !Array.isArray(rpcResult.accepted) || rpcResult.accepted.length === 0) {
    throw new Error('upsert_progress_batch did not report accepted events');
  }

  const courseProgress = await client.query(
    `select progress from user_course_progress where user_id = $1 and course_id = $2`,
    [event.user_id, courseId],
  );
  if (courseProgress.rows.length === 0) {
    throw new Error('user_course_progress row missing after progress batch');
  }

  const lessonProgress = await client.query(
    `select progress from user_lesson_progress where user_id = $1 and lesson_id = $2`,
    [event.user_id, lessonId],
  );
  if (lessonProgress.rows.length === 0) {
    throw new Error('user_lesson_progress row missing after progress batch');
  }
});

await client.end();

const failed = results.filter((r) => !r.success);
if (failed.length) {
  console.error(`❌ ${failed.length} DB function test(s) failed.`);
  process.exit(1);
}

console.log('🎉 All DB function smoke-tests passed.');
