-- Consolidate multiple permissive RLS policies into one for storage.objects
-- Generated by scripts/generate_consolidation_migrations.mjs on 2026-05-02T22:12:47.089Z

-- NOTE: This creates a consolidated policy combining existing USING conditions with OR.
-- Verify application behavior after applying. Keep backups of original policies until verified.

-- Optional: drop old policies after verification (commented out below)
-- DROP POLICY IF EXISTS Users update own avatars ON storage.objects;
-- DROP POLICY IF EXISTS Org members update org-assets ON storage.objects;
-- DROP POLICY IF EXISTS Authenticated update own avatars + org-assets ON storage.objects;

CREATE POLICY consolidated_authenticated_update ON storage.objects FOR UPDATE TO authenticated USING ((((bucket_id = 'avatars'::text) AND (owner = auth.uid()))) OR (((bucket_id = 'org-assets'::text) AND (EXISTS ( SELECT 1
   FROM organization_memberships m
  WHERE ((m.user_id = auth.uid()) AND (m.organization_id = (split_part(objects.name, '/'::text, 1))::uuid)))))) OR (((bucket_id = ANY (ARRAY['avatars'::text, 'org-assets'::text])) AND (owner = auth.uid())))) WITH CHECK ((((bucket_id = 'avatars'::text) AND (owner = auth.uid()))) OR (((bucket_id = 'org-assets'::text) AND (EXISTS ( SELECT 1
   FROM organization_memberships m
  WHERE ((m.user_id = auth.uid()) AND (m.organization_id = (split_part(objects.name, '/'::text, 1))::uuid)))))) OR (((bucket_id = ANY (ARRAY['avatars'::text, 'org-assets'::text])) AND (owner = auth.uid()))));

-- After verifying behavior, you may DROP the old policies and optionally rename this policy.
