import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useParams, Link, useNavigate } from 'react-router-dom';
import SEO from '../../components/SEO/SEO';
import Card from '../../components/ui/Card';
import Button from '../../components/ui/Button';
import Breadcrumbs from '../../components/ui/Breadcrumbs';
const AdminCoursePreview = () => {
    const { courseId } = useParams();
    const navigate = useNavigate();
    return (_jsxs("div", { className: "p-6 max-w-6xl mx-auto", children: [_jsx(SEO, { title: "Admin - Course Preview", description: "Preview how this course appears to learners." }), _jsx(Breadcrumbs, { items: [{ label: 'Admin', to: '/admin' }, { label: 'Courses', to: '/admin/courses' }, { label: 'Preview', to: `/admin/courses/${courseId}/preview` }] }), _jsxs("div", { className: "mt-4", children: [_jsx("h1", { className: "text-2xl font-bold text-gray-900", children: "Course Preview" }), _jsxs("p", { className: "text-sm text-gray-600 mt-1", children: ["Quick look at the learner-facing presentation for course ", _jsx("span", { className: "font-mono text-gray-800", children: courseId }), "."] })] }), _jsxs("div", { className: "mt-6 grid gap-6 lg:grid-cols-[320px,1fr]", children: [_jsx(Card, { tone: "muted", className: "h-full", children: _jsxs("div", { className: "space-y-3", children: [_jsx("p", { className: "text-sm text-slate/80", children: "Use these actions to manage this course." }), _jsxs("div", { className: "flex flex-col gap-2", children: [_jsx(Button, { asChild: true, size: "sm", variant: "secondary", children: _jsx(Link, { to: "/admin/courses", children: "Back to Courses" }) }), _jsx(Button, { size: "sm", onClick: () => navigate(`/admin/courses/${courseId}/edit`), children: "Edit Course" }), _jsx(Button, { size: "sm", variant: "outline", onClick: () => navigate(`/admin/courses/${courseId}/assign`), children: "Assign Course" })] })] }) }), _jsxs(Card, { padding: "lg", className: "min-h-[280px]", children: [_jsx("div", { className: "text-sm text-slate/80", children: "This is a lightweight preview placeholder. To view a full learner experience, open the course from the client catalog or use the player routes. You can wire a dedicated preview here later." }), _jsx("div", { className: "mt-4", children: _jsx(Button, { asChild: true, variant: "ghost", size: "sm", children: _jsx(Link, { to: `/client/courses/${courseId}`, children: "Open client course overview \u2192" }) }) })] })] })] }));
};
export default AdminCoursePreview;
