"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var react_router_dom_1 = require("react-router-dom");
var SEO_1 = require("../../components/SEO/SEO");
var Card_1 = require("../../components/ui/Card");
var Button_1 = require("../../components/ui/Button");
var Breadcrumbs_1 = require("../../components/ui/Breadcrumbs");
var AdminCoursePreview = function () {
    var courseId = (0, react_router_dom_1.useParams)().courseId;
    var navigate = (0, react_router_dom_1.useNavigate)();
    return ((0, jsx_runtime_1.jsxs)("div", { className: "p-6 max-w-6xl mx-auto", children: [(0, jsx_runtime_1.jsx)(SEO_1.default, { title: "Admin - Course Preview", description: "Preview how this course appears to learners." }), (0, jsx_runtime_1.jsx)(Breadcrumbs_1.default, { items: [{ label: 'Admin', to: '/admin' }, { label: 'Courses', to: '/admin/courses' }, { label: 'Preview', to: "/admin/courses/".concat(courseId, "/preview") }] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-4", children: [(0, jsx_runtime_1.jsx)("h1", { className: "text-2xl font-bold text-gray-900", children: "Course Preview" }), (0, jsx_runtime_1.jsxs)("p", { className: "text-sm text-gray-600 mt-1", children: ["Quick look at the learner-facing presentation for course ", (0, jsx_runtime_1.jsx)("span", { className: "font-mono text-gray-800", children: courseId }), "."] })] }), (0, jsx_runtime_1.jsxs)("div", { className: "mt-6 grid gap-6 lg:grid-cols-[320px,1fr]", children: [(0, jsx_runtime_1.jsx)(Card_1.default, { tone: "muted", className: "h-full", children: (0, jsx_runtime_1.jsxs)("div", { className: "space-y-3", children: [(0, jsx_runtime_1.jsx)("p", { className: "text-sm text-slate/80", children: "Use these actions to manage this course." }), (0, jsx_runtime_1.jsxs)("div", { className: "flex flex-col gap-2", children: [(0, jsx_runtime_1.jsx)(Button_1.default, { asChild: true, size: "sm", variant: "secondary", children: (0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: "/admin/courses", children: "Back to Courses" }) }), (0, jsx_runtime_1.jsx)(Button_1.default, { size: "sm", onClick: function () { return navigate("/admin/courses/".concat(courseId, "/edit")); }, children: "Edit Course" }), (0, jsx_runtime_1.jsx)(Button_1.default, { size: "sm", variant: "outline", onClick: function () { return navigate("/admin/courses/".concat(courseId, "/assign")); }, children: "Assign Course" })] })] }) }), (0, jsx_runtime_1.jsxs)(Card_1.default, { padding: "lg", className: "min-h-[280px]", children: [(0, jsx_runtime_1.jsx)("div", { className: "text-sm text-slate/80", children: "This is a lightweight preview placeholder. To view a full learner experience, open the course from the client catalog or use the player routes. You can wire a dedicated preview here later." }), (0, jsx_runtime_1.jsx)("div", { className: "mt-4", children: (0, jsx_runtime_1.jsx)(Button_1.default, { asChild: true, variant: "ghost", size: "sm", children: (0, jsx_runtime_1.jsx)(react_router_dom_1.Link, { to: "/client/courses/".concat(courseId), children: "Open client course overview \u2192" }) }) })] })] })] }));
};
exports.default = AdminCoursePreview;
